service: <%= ENV.fetch("SERVICE_NAME", File.basename(File.expand_path("..", __FILE__))) %>
image: tifandotme/<%= ENV.fetch("SERVICE_NAME", File.basename(File.expand_path("..", __FILE__))) %>

servers:
  web:
    hosts:
      - box.javanese-pound.ts.net
    options:
      memory: 2g

ssh:
  user: eddies

sshkit:
  max_concurrent_starts: 1
  dns_retries: 5
  pool_idle_timeout: 300

proxy:
  # using custom cert
  # because Kamal's `ssl: true` feature won't work when the server is "private"
  # p.s. we need to renew it every 3 months
  ssl:
    certificate_pem: SSL_CERTIFICATE_PEM
    private_key_pem: SSL_PRIVATE_KEY_PEM
  host: hermes.tifan.me
  app_port: 9119
  healthcheck:
    path: /api/status
    interval: 30
    timeout: 15

env:
  clear:
    HERMES_HOME: /opt/data
    HERMES_DASHBOARD: "1"
    HERMES_DASHBOARD_HOST: "0.0.0.0"
    HERMES_DASHBOARD_PORT: "9119"
    HERMES_DASHBOARD_PUBLIC_URL: https://hermes.tifan.me
    HERMES_DASHBOARD_INSECURE: "1"
    TZ: Asia/Jakarta
    TERM: xterm-256color

volumes:
  - /home/eddies/hermes-storage:/opt/data

registry:
  server: ghcr.io
  username:
    - KAMAL_REGISTRY_USERNAME
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64
  remote: ssh://eddies@box.javanese-pound.ts.net
  args:
    IMAGE: <%= ENV.fetch("IMAGE") %>
    VERSION: <%= ENV.fetch("VERSION", "latest") %>
    SERVICE_NAME: <%= ENV.fetch("SERVICE_NAME", File.basename(File.expand_path("..", __FILE__))) %>
    HERMES_UID: 1001
    HERMES_GID: 1001

deploy_timeout: 180
drain_timeout: 30
