#!/usr/bin/env bash

#MISE description="Run linuxbrew program in server"

#USAGE arg "<program>" help="Program to run" {
#USAGE   choices "btm" "lazydocker" "ctop"
#USAGE }

set -e

PROGRAM="${usage_program?}"

cd "n8n" # defaults

dotenvx run -- kamal server exec --interactive "TERM=xterm-256color /home/linuxbrew/.linuxbrew/bin/$PROGRAM"
