#!/usr/bin/env bash

#MISE description="Execute a shell in the specified directory's app container using Kamal"

#USAGE arg "<dir>" help="Directory to exec into"

set -e

cd "${usage_dir?}"

dotenvx run -- kamal app exec --interactive --reuse "bash"
