#!/usr/bin/env bash

#MISE description="Exec into apps"

#USAGE arg "<app>" help="App directory to deploy" {
#USAGE   choices "n8n" "fizzy" "uptime-kuma"
#USAGE }

set -e

export SERVICE_NAME="${usage_app?}"
cd "$SERVICE_NAME" || {
  echo "App directory '$SERVICE_NAME' not found"
  exit 1
}

dotenvx run -- kamal app exec --interactive --reuse "bash"
