FROM louislam/uptime-kuma:latest

LABEL service="uptime-kuma"

# Change app UID to match host eddies UID for volume ownership
# USER root
# RUN usermod -u 1001 node
# RUN chown -R node /app
# USER node
